# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2025.2.2\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2025.2.2\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\joaop\UFRGS\CPD\IMDB_Query - Copia"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\joaop\UFRGS\CPD\IMDB_Query - Copia\cmake-build-debug"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2025.2.2\bin\cmake\win\x64\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2025.2.2\bin\cmake\win\x64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\joaop\UFRGS\CPD\IMDB_Query - Copia\cmake-build-debug\CMakeFiles" "C:\Users\joaop\UFRGS\CPD\IMDB_Query - Copia\cmake-build-debug\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\joaop\UFRGS\CPD\IMDB_Query - Copia\cmake-build-debug\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IMDB_Query

# Build rule for target.
IMDB_Query: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 IMDB_Query
.PHONY : IMDB_Query

# fast build rule for target.
IMDB_Query/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/build
.PHONY : IMDB_Query/fast

IQuery.obj: IQuery.c.obj
.PHONY : IQuery.obj

# target to build an object file
IQuery.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/IQuery.c.obj
.PHONY : IQuery.c.obj

IQuery.i: IQuery.c.i
.PHONY : IQuery.i

# target to preprocess a source file
IQuery.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/IQuery.c.i
.PHONY : IQuery.c.i

IQuery.s: IQuery.c.s
.PHONY : IQuery.s

# target to generate assembly for a file
IQuery.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/IQuery.c.s
.PHONY : IQuery.c.s

apiHandler.obj: apiHandler.c.obj
.PHONY : apiHandler.obj

# target to build an object file
apiHandler.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/apiHandler.c.obj
.PHONY : apiHandler.c.obj

apiHandler.i: apiHandler.c.i
.PHONY : apiHandler.i

# target to preprocess a source file
apiHandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/apiHandler.c.i
.PHONY : apiHandler.c.i

apiHandler.s: apiHandler.c.s
.PHONY : apiHandler.s

# target to generate assembly for a file
apiHandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/apiHandler.c.s
.PHONY : apiHandler.c.s

binService.obj: binService.c.obj
.PHONY : binService.obj

# target to build an object file
binService.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/binService.c.obj
.PHONY : binService.c.obj

binService.i: binService.c.i
.PHONY : binService.i

# target to preprocess a source file
binService.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/binService.c.i
.PHONY : binService.c.i

binService.s: binService.c.s
.PHONY : binService.s

# target to generate assembly for a file
binService.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/binService.c.s
.PHONY : binService.c.s

dbContext.obj: dbContext.c.obj
.PHONY : dbContext.obj

# target to build an object file
dbContext.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/dbContext.c.obj
.PHONY : dbContext.c.obj

dbContext.i: dbContext.c.i
.PHONY : dbContext.i

# target to preprocess a source file
dbContext.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/dbContext.c.i
.PHONY : dbContext.c.i

dbContext.s: dbContext.c.s
.PHONY : dbContext.s

# target to generate assembly for a file
dbContext.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/dbContext.c.s
.PHONY : dbContext.c.s

entities.obj: entities.c.obj
.PHONY : entities.obj

# target to build an object file
entities.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/entities.c.obj
.PHONY : entities.c.obj

entities.i: entities.c.i
.PHONY : entities.i

# target to preprocess a source file
entities.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/entities.c.i
.PHONY : entities.c.i

entities.s: entities.c.s
.PHONY : entities.s

# target to generate assembly for a file
entities.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/entities.c.s
.PHONY : entities.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/main.c.s
.PHONY : main.c.s

postings.obj: postings.c.obj
.PHONY : postings.obj

# target to build an object file
postings.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/postings.c.obj
.PHONY : postings.c.obj

postings.i: postings.c.i
.PHONY : postings.i

# target to preprocess a source file
postings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/postings.c.i
.PHONY : postings.c.i

postings.s: postings.c.s
.PHONY : postings.s

# target to generate assembly for a file
postings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/postings.c.s
.PHONY : postings.c.s

sysManager.obj: sysManager.c.obj
.PHONY : sysManager.obj

# target to build an object file
sysManager.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/sysManager.c.obj
.PHONY : sysManager.c.obj

sysManager.i: sysManager.c.i
.PHONY : sysManager.i

# target to preprocess a source file
sysManager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/sysManager.c.i
.PHONY : sysManager.c.i

sysManager.s: sysManager.c.s
.PHONY : sysManager.s

# target to generate assembly for a file
sysManager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/sysManager.c.s
.PHONY : sysManager.c.s

util.obj: util.c.obj
.PHONY : util.obj

# target to build an object file
util.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/util.c.obj
.PHONY : util.c.obj

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IMDB_Query.dir\build.make CMakeFiles/IMDB_Query.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... IMDB_Query
	@echo ... IQuery.obj
	@echo ... IQuery.i
	@echo ... IQuery.s
	@echo ... apiHandler.obj
	@echo ... apiHandler.i
	@echo ... apiHandler.s
	@echo ... binService.obj
	@echo ... binService.i
	@echo ... binService.s
	@echo ... dbContext.obj
	@echo ... dbContext.i
	@echo ... dbContext.s
	@echo ... entities.obj
	@echo ... entities.i
	@echo ... entities.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... postings.obj
	@echo ... postings.i
	@echo ... postings.s
	@echo ... sysManager.obj
	@echo ... sysManager.i
	@echo ... sysManager.s
	@echo ... util.obj
	@echo ... util.i
	@echo ... util.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

